apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      containers:
      - name: job-container
        image: busybox
        command: ["sh", "-c" "echo Hello kubernetes! && sleep 5"]
      restartPolicy: Never

